### ISSUE TITLE
UHD Blu-ray support

### ISSUE THREAD

**Issue by JackDash** [Rupan/BDInfo#6]
Now that AACS 2.0 encryption has apparently been cracked, it is now possible to make a direct copy of a UHD Blu-ray. These use the same file structure as regular Blu-rays, but BDInfo is unable to scan them so far.

Any chance of seeing UHD Blu-ray support?

**Comment by Musashii-kun** [comment]
From what I read in the news, the contents of one single disc image was released.  Let's wait and see if/when new disc images are made available, and if any of the commercial decryptors add support.

**Comment by dancingnzb** [comment]
Hello,

Is this going to be implemented in linux using CLi any time soon ? 

I believe DVDFab seems to have their own BDInfo that scans UHD discs fine.

**Comment by git4kUHD** [comment]
I have fixed this issue for you. Any way I can contribute my changes and share with everyone? You can download an updated compiled version [here](https://www.videohelp.com/software/BDInfo).

**Comment by manuelrn** [comment]
Thanks @git4kUHD, your new version also add support for DTS:X & Dolby Atmos tracks?

**Comment by Sparktank** [comment]
@git4kUHD can you add your changes to a repository on your github?

**Comment by git4kUHD** [comment]
@manuelrn - No, not yet. This bug is for BDInfo not being able to parse a UHD disc. This is now resolved, though parsing audio tracks is the same and will show DTS:X as DTS-HD MA and Atmos as TrueHD. I plan to work on this as well, but that would be a future update. I thought it important to add UHD playlist support first.

@Sparktank - I haven't created a personal repository yet. I'm open to this, though I was hoping @Rupan would let me contribute here. If he doesn't respond, then I will put my code somewhere on GitHub, and let everyone know.

**Comment by Musashii-kun** [comment]
Sure, you can contribute here.  The easiest way is to submit a pull request, but you'd need to have a fork of this repository on Github to do that.  Alternately, if you upload an archive of your source code somewhere, I can apply the patch to this repository myself.

**Comment by ordinarygulp** [comment]
@git4kUHD for me, I can still not scan a BD with HEVC stream on your version of BDInfo. I can see playlists, but not get stream information/bitrates.

**Comment by git4kUHD** [comment]
@d2dyno - You are correct. I was just excited to be able to parse the playlists to the streams. I did miss the HEVC video streams are not showing up. I will look into it. Thanks!

@Rupan, I will look at forking and contributing soon.

**Comment by nautilus7** [comment]
@git4kUHD With your 0.5.10 version when the report is generated and you hit "view report --> generate graph" I get a crash every time: https://pastebin.com/VCF3xN0y

Where I can find your source code? I believe you should post it somewhere online to be accessible.

**Comment by git4kUHD** [comment]
@nautilus7, I underestimated what needed to be changed in the current version. I was able to parse the clips and playlists, but much of the stream detail isn't working yet for HEVC video streams. It should still function the same for regular blu-ray, so you're not losing any functionality. Complete support for UHD still isn't there. I'm actively working on it.

I am looking at integrating MediaInfo into the application to get better (updated) support for more codec types. They seem to be the authority on parsing Atmos & DTS:X tracks, along with many other codecs. Anyone have an opinion about going this direction? The GUI and functionality will remain the same, but the stream data would rely on MediaInfo instead of parsing the stream data directly.

As for code sharing, I will share my repository with the next version and will welcome community contributions. The next version needs some work though, so I don't have a time-frame on when that will happen. You can also go back to using v0.5.9 if you prefer while I keep working on this.

**Comment by Sparktank** [comment]
The nice thing about public github is that viewers can at least view the progress and ideas, and if real life becomes too much for you, someone else can contribute with the same ideas.
Who knows, someone might know exactly where to go with your ideas.
But if the code remains hidden, everyone else has to work from the ground-up.
TsMuxeR was doing great until the author of the recent updates didn't get around to sharing the source code publicly on github, or elsewhere.

The largest drawback to open-source is the authors not posting, even for posterity.

The largest benefit to open-source is that the current progress should be available at least somewhere.

**Comment by tlochner** [comment]
i have a problem where the hevc video is not listed in the report. 
running win 7, net frame 4.6.1.
